"""create initial idealens schema

Revision ID: b879365f4cac
Revises: 
Create Date: 2026-09-04 20:24:09.801651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b879365f4cac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('decision_signal', sa.Integer(), nullable=False),
    sa.Column('disclosure', sa.Text(), nullable=False),
    sa.Column('decomposition', sa.JSON(), nullable=True),
    sa.Column('scoring_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('provider_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_created_at'), 'research_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_source_document_id'), 'research_runs', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_table('source_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adapter_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider_schema_version', sa.String(length=32), nullable=False),
    sa.Column('credentials_configured', sa.Boolean(), nullable=False),
    sa.Column('last_health', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_profiles_adapter_id'), 'source_profiles', ['adapter_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_run_id'), 'claims', ['run_id'], unique=False)
    op.create_table('collision_combinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('component_ids', sa.JSON(), nullable=True),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collision_combinations_run_id'), 'collision_combinations', ['run_id'], unique=False)
    op.create_table('coverage_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_results_dimension'), 'coverage_results', ['dimension'], unique=False)
    op.create_index(op.f('ix_coverage_results_run_id'), 'coverage_results', ['run_id'], unique=False)
    op.create_table('differentiation_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('overlap_summary', sa.Text(), nullable=False),
    sa.Column('overlap_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('differentiation_hypothesis', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('less_represented_area', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('remaining_uncertainty', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_differentiation_recommendations_run_id'), 'differentiation_recommendations', ['run_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('extracted_title', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_hash_sha256'), 'documents', ['hash_sha256'], unique=False)
    op.create_index(op.f('ix_documents_run_id'), 'documents', ['run_id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_run_id'), 'graph_nodes', ['run_id'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_run_id'), 'queries', ['run_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('scope_disclosure', sa.JSON(), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=True),
    sa.Column('language_guardrail_status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_run_id'), 'reports', ['run_id'], unique=True)
    op.create_table('research_gaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('scope_kind', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.JSON(), nullable=True),
    sa.Column('saturation_bucket', sa.String(length=40), nullable=False),
    sa.Column('standardized_language', sa.Text(), nullable=False),
    sa.Column('coverage_disclosure', sa.JSON(), nullable=True),
    sa.Column('evidence_basis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_gaps_run_id'), 'research_gaps', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_event_type'), 'run_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('similarity_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('lexical_score', sa.Float(), nullable=True),
    sa.Column('structured_score', sa.Float(), nullable=True),
    sa.Column('embedding_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarity_results_dimension'), 'similarity_results', ['dimension'], unique=False)
    op.create_index(op.f('ix_similarity_results_run_id'), 'similarity_results', ['run_id'], unique=False)
    op.create_table('source_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('adapter_id', sa.String(length=32), nullable=False),
    sa.Column('global_normalized_id', sa.String(length=128), nullable=False),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('identifiers', sa.JSON(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('abstract_or_description', sa.Text(), nullable=True),
    sa.Column('primary_url', sa.String(length=512), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_status', sa.String(length=24), nullable=False),
    sa.Column('canonical_id', sa.Uuid(), nullable=True),
    sa.Column('quality_signals', sa.JSON(), nullable=True),
    sa.Column('fetch_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_items_adapter_id'), 'source_items', ['adapter_id'], unique=False)
    op.create_index(op.f('ix_source_items_global_normalized_id'), 'source_items', ['global_normalized_id'], unique=False)
    op.create_index(op.f('ix_source_items_retrieved_at'), 'source_items', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_source_items_run_id'), 'source_items', ['run_id'], unique=False)
    op.create_table('stress_test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_test_results_run_id'), 'stress_test_results', ['run_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('ord_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_span', sa.JSON(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('excerpt_span', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.String(length=16), nullable=False),
    sa.Column('provenance_backref', sa.JSON(), nullable=True),
    sa.Column('retrieval_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_dimension'), 'evidence', ['dimension'], unique=False)
    op.create_index(op.f('ix_evidence_run_id'), 'evidence', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_item_id'), 'evidence', ['source_item_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_run_id'), 'graph_edges', ['run_id'], unique=False)
    op.create_table('contradictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('evidence_a_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_b_id', sa.Uuid(), nullable=True),
    sa.Column('source_a_id', sa.Uuid(), nullable=True),
    sa.Column('source_b_id', sa.Uuid(), nullable=True),
    sa.Column('comparability', sa.String(length=24), nullable=False),
    sa.Column('conflict_summary', sa.Text(), nullable=False),
    sa.Column('possible_explanations', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['source_a_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['source_b_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contradictions_dimension'), 'contradictions', ['dimension'], unique=False)
    op.create_index(op.f('ix_contradictions_run_id'), 'contradictions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contradictions_run_id'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_dimension'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index(op.f('ix_graph_edges_run_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_evidence_source_item_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_run_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_dimension'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_stress_test_results_run_id'), table_name='stress_test_results')
    op.drop_table('stress_test_results')
    op.drop_index(op.f('ix_source_items_run_id'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_retrieved_at'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_global_normalized_id'), table_name='source_items')
    op.drop_index(op.f('ix_source_items_adapter_id'), table_name='source_items')
    op.drop_table('source_items')
    op.drop_index(op.f('ix_similarity_results_run_id'), table_name='similarity_results')
    op.drop_index(op.f('ix_similarity_results_dimension'), table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_event_type'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_research_gaps_run_id'), table_name='research_gaps')
    op.drop_table('research_gaps')
    op.drop_index(op.f('ix_reports_run_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_queries_run_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_graph_nodes_run_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_documents_run_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_hash_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_differentiation_recommendations_run_id'), table_name='differentiation_recommendations')
    op.drop_table('differentiation_recommendations')
    op.drop_index(op.f('ix_coverage_results_run_id'), table_name='coverage_results')
    op.drop_index(op.f('ix_coverage_results_dimension'), table_name='coverage_results')
    op.drop_table('coverage_results')
    op.drop_index(op.f('ix_collision_combinations_run_id'), table_name='collision_combinations')
    op.drop_table('collision_combinations')
    op.drop_index(op.f('ix_claims_run_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_source_profiles_adapter_id'), table_name='source_profiles')
    op.drop_table('source_profiles')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_source_document_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_created_at'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
